// Real Jharkhand State Healthcare Dataset & Structure
// 24 Districts, 79 Government Hospitals (Medical Colleges, Sadar Hospitals, SDHs, CHCs)
import type { Hospital, NetworkEdge } from "./triage-data"

export interface JharkhandDistrict {
  id: string
  name: string
  cmoName: string
  cmoPhone: string
  lat: number
  lng: number
}

export interface JharkhandHospitalFacility {
  id: string
  name: string
  shortCode: string
  districtName: string
  facilityTier: "TERTIARY" | "DISTRICT" | "SUB_DIVISIONAL" | "CHC"
  latitude: number
  longitude: number
  totalGeneralBeds: number
  availableGeneralBeds: number
  totalIcuBeds: number
  availableIcuBeds: number
  totalVentilators: number
  availableVentilators: number
  hasVentilator: boolean
  hasTraumaSurgery: boolean
  hasBloodBank: boolean
  hasOxygenGenerator: boolean
  specialists: string[]
}

export const JHARKHAND_24_DISTRICTS: JharkhandDistrict[] = [
  {
    "id": "ranchi",
    "name": "Ranchi",
    "cmoName": "Dr. Prabhat Kumar",
    "cmoPhone": "+91-651-2200101",
    "lat": 23.3441,
    "lng": 85.3096
  },
  {
    "id": "east-singhbhum-jamshedpur-",
    "name": "East Singhbhum (Jamshedpur)",
    "cmoName": "Dr. Sahir Pall",
    "cmoPhone": "+91-657-2431022",
    "lat": 22.8046,
    "lng": 86.2029
  },
  {
    "id": "dhanbad",
    "name": "Dhanbad",
    "cmoName": "Dr. C.B. Pratap",
    "cmoPhone": "+91-654-2220303",
    "lat": 23.7957,
    "lng": 86.4304
  },
  {
    "id": "bokaro",
    "name": "Bokaro",
    "cmoName": "Dr. A.B. Prasad",
    "cmoPhone": "+91-654-2420404",
    "lat": 23.6693,
    "lng": 86.1511
  },
  {
    "id": "hazaribagh",
    "name": "Hazaribagh",
    "cmoName": "Dr. S.P. Singh",
    "cmoPhone": "+91-654-2620505",
    "lat": 23.9925,
    "lng": 85.3637
  },
  {
    "id": "palamu-daltonganj-",
    "name": "Palamu (Daltonganj)",
    "cmoName": "Dr. Anil Kumar",
    "cmoPhone": "+91-656-2220606",
    "lat": 24.0372,
    "lng": 84.0722
  },
  {
    "id": "deoghar",
    "name": "Deoghar",
    "cmoName": "Dr. R.N. Prasad",
    "cmoPhone": "+91-643-2230707",
    "lat": 24.4826,
    "lng": 86.6961
  },
  {
    "id": "giridih",
    "name": "Giridih",
    "cmoName": "Dr. Siddharth Soman",
    "cmoPhone": "+91-653-2220808",
    "lat": 24.19,
    "lng": 86.3
  },
  {
    "id": "dumka",
    "name": "Dumka",
    "cmoName": "Dr. B.K. Saha",
    "cmoPhone": "+91-643-2220909",
    "lat": 24.2676,
    "lng": 87.2497
  },
  {
    "id": "ramgarh",
    "name": "Ramgarh",
    "cmoName": "Dr. Neelam Chaudhary",
    "cmoPhone": "+91-655-2221010",
    "lat": 23.6293,
    "lng": 85.5167
  },
  {
    "id": "west-singhbhum-chaibasa-",
    "name": "West Singhbhum (Chaibasa)",
    "cmoName": "Dr. Om Prakash",
    "cmoPhone": "+91-658-2221111",
    "lat": 22.5517,
    "lng": 85.8086
  },
  {
    "id": "koderma",
    "name": "Koderma",
    "cmoName": "Dr. Parvati Kumari",
    "cmoPhone": "+91-653-2221212",
    "lat": 24.4674,
    "lng": 85.5936
  },
  {
    "id": "chatra",
    "name": "Chatra",
    "cmoName": "Dr. S.N. Singh",
    "cmoPhone": "+91-654-2221313",
    "lat": 24.2167,
    "lng": 84.8667
  },
  {
    "id": "garhwa",
    "name": "Garhwa",
    "cmoName": "Dr. N.K. Pandey",
    "cmoPhone": "+91-656-2221414",
    "lat": 24.1557,
    "lng": 83.8078
  },
  {
    "id": "latehar",
    "name": "Latehar",
    "cmoName": "Dr. Dinesh Kumar",
    "cmoPhone": "+91-656-2221515",
    "lat": 23.7436,
    "lng": 84.4984
  },
  {
    "id": "lohardaga",
    "name": "Lohardaga",
    "cmoName": "Dr. S.K. Roy",
    "cmoPhone": "+91-652-2221616",
    "lat": 23.4319,
    "lng": 84.68
  },
  {
    "id": "gumla",
    "name": "Gumla",
    "cmoName": "Dr. R.K. Soren",
    "cmoPhone": "+91-652-2221717",
    "lat": 22.9989,
    "lng": 84.5422
  },
  {
    "id": "simdega",
    "name": "Simdega",
    "cmoName": "Dr. A.K. Minz",
    "cmoPhone": "+91-652-2221818",
    "lat": 22.6143,
    "lng": 84.5097
  },
  {
    "id": "khunti",
    "name": "Khunti",
    "cmoName": "Dr. Lobsang Hembrom",
    "cmoPhone": "+91-652-2221919",
    "lat": 23.076,
    "lng": 85.2789
  },
  {
    "id": "seraikela-kharsawan",
    "name": "Seraikela Kharsawan",
    "cmoName": "Dr. Vijay Kumar",
    "cmoPhone": "+91-658-2222020",
    "lat": 22.7001,
    "lng": 85.9298
  },
  {
    "id": "jamtara",
    "name": "Jamtara",
    "cmoName": "Dr. S.K. Mishra",
    "cmoPhone": "+91-643-2222121",
    "lat": 23.9627,
    "lng": 86.8021
  },
  {
    "id": "godda",
    "name": "Godda",
    "cmoName": "Dr. Anant Jha",
    "cmoPhone": "+91-643-2222222",
    "lat": 24.8277,
    "lng": 87.2122
  },
  {
    "id": "sahibganj",
    "name": "Sahibganj",
    "cmoName": "Dr. Ram Subhag",
    "cmoPhone": "+91-643-2222323",
    "lat": 25.2425,
    "lng": 87.6419
  },
  {
    "id": "pakur",
    "name": "Pakur",
    "cmoName": "Dr. M.K. Bhagat",
    "cmoPhone": "+91-643-2222424",
    "lat": 24.6346,
    "lng": 87.8486
  }
];

export const JHARKHAND_79_HOSPITALS: JharkhandHospitalFacility[] = [
  {
    "id": "jh-rajendra-institute-of-medical-sciences-rims",
    "name": "Rajendra Institute of Medical Sciences (RIMS)",
    "shortCode": "RIMS",
    "districtName": "Ranchi",
    "facilityTier": "TERTIARY",
    "latitude": 23.3888,
    "longitude": 85.3582,
    "totalGeneralBeds": 1500,
    "availableGeneralBeds": 320,
    "totalIcuBeds": 150,
    "availableIcuBeds": 18,
    "totalVentilators": 90,
    "availableVentilators": 23,
    "hasVentilator": true,
    "hasTraumaSurgery": true,
    "hasBloodBank": true,
    "hasOxygenGenerator": true,
    "specialists": [
      "Pulmonologist",
      "Cardiologist",
      "Trauma Surgeon",
      "Neurologist",
      "Nephrologist"
    ]
  },
  {
    "id": "jh-mgm-medical-college-and-hospital",
    "name": "MGM Medical College and Hospital",
    "shortCode": "MMCH",
    "districtName": "East Singhbhum (Jamshedpur)",
    "facilityTier": "TERTIARY",
    "latitude": 22.8258,
    "longitude": 86.2163,
    "totalGeneralBeds": 600,
    "availableGeneralBeds": 110,
    "totalIcuBeds": 60,
    "availableIcuBeds": 8,
    "totalVentilators": 36,
    "availableVentilators": 9,
    "hasVentilator": true,
    "hasTraumaSurgery": true,
    "hasBloodBank": true,
    "hasOxygenGenerator": true,
    "specialists": [
      "Pulmonologist",
      "Cardiologist",
      "Trauma Surgeon"
    ]
  },
  {
    "id": "jh-shahid-nirmal-mahto-medical-college-hospital-snmmch-pmch",
    "name": "Shahid Nirmal Mahto Medical College Hospital (SNMMCH / PMCH)",
    "shortCode": "SNMMC",
    "districtName": "Dhanbad",
    "facilityTier": "TERTIARY",
    "latitude": 23.8111,
    "longitude": 86.4389,
    "totalGeneralBeds": 550,
    "availableGeneralBeds": 95,
    "totalIcuBeds": 50,
    "availableIcuBeds": 5,
    "totalVentilators": 30,
    "availableVentilators": 8,
    "hasVentilator": true,
    "hasTraumaSurgery": true,
    "hasBloodBank": true,
    "hasOxygenGenerator": true,
    "specialists": [
      "Pulmonologist",
      "Cardiologist",
      "Trauma Surgeon"
    ]
  },
  {
    "id": "jh-aiims-deoghar",
    "name": "AIIMS Deoghar",
    "shortCode": "AD",
    "districtName": "Deoghar",
    "facilityTier": "TERTIARY",
    "latitude": 24.4632,
    "longitude": 86.7214,
    "totalGeneralBeds": 750,
    "availableGeneralBeds": 180,
    "totalIcuBeds": 80,
    "availableIcuBeds": 22,
    "totalVentilators": 48,
    "availableVentilators": 12,
    "hasVentilator": true,
    "hasTraumaSurgery": true,
    "hasBloodBank": true,
    "hasOxygenGenerator": true,
    "specialists": [
      "Pulmonologist",
      "Cardiologist",
      "Trauma Surgeon",
      "Neurologist"
    ]
  },
  {
    "id": "jh-sheikh-bhikari-medical-college-and-hospital",
    "name": "Sheikh Bhikari Medical College and Hospital",
    "shortCode": "SBMCH",
    "districtName": "Hazaribagh",
    "facilityTier": "TERTIARY",
    "latitude": 23.9982,
    "longitude": 85.3688,
    "totalGeneralBeds": 500,
    "availableGeneralBeds": 85,
    "totalIcuBeds": 40,
    "availableIcuBeds": 6,
    "totalVentilators": 24,
    "availableVentilators": 6,
    "hasVentilator": true,
    "hasTraumaSurgery": true,
    "hasBloodBank": true,
    "hasOxygenGenerator": true,
    "specialists": [
      "Pulmonologist",
      "Trauma Surgeon"
    ]
  },
  {
    "id": "jh-medinirai-medical-college-and-hospital",
    "name": "Medinirai Medical College and Hospital",
    "shortCode": "MMCH",
    "districtName": "Palamu (Daltonganj)",
    "facilityTier": "TERTIARY",
    "latitude": 24.0415,
    "longitude": 84.0811,
    "totalGeneralBeds": 450,
    "availableGeneralBeds": 70,
    "totalIcuBeds": 35,
    "availableIcuBeds": 4,
    "totalVentilators": 21,
    "availableVentilators": 5,
    "hasVentilator": true,
    "hasTraumaSurgery": true,
    "hasBloodBank": true,
    "hasOxygenGenerator": true,
    "specialists": [
      "Pulmonologist",
      "Cardiologist"
    ]
  },
  {
    "id": "jh-phulo-jhano-medical-college-and-hospital",
    "name": "Phulo Jhano Medical College and Hospital",
    "shortCode": "PJMCH",
    "districtName": "Dumka",
    "facilityTier": "TERTIARY",
    "latitude": 24.2715,
    "longitude": 87.253,
    "totalGeneralBeds": 500,
    "availableGeneralBeds": 105,
    "totalIcuBeds": 40,
    "availableIcuBeds": 7,
    "totalVentilators": 24,
    "availableVentilators": 6,
    "hasVentilator": true,
    "hasTraumaSurgery": true,
    "hasBloodBank": true,
    "hasOxygenGenerator": true,
    "specialists": [
      "Pulmonologist",
      "Trauma Surgeon"
    ]
  },
  {
    "id": "jh-sadar-district-hospital-ranchi",
    "name": "Sadar District Hospital Ranchi",
    "shortCode": "SDHR",
    "districtName": "Ranchi",
    "facilityTier": "DISTRICT",
    "latitude": 23.3478,
    "longitude": 85.29,
    "totalGeneralBeds": 277,
    "availableGeneralBeds": 60,
    "totalIcuBeds": 19,
    "availableIcuBeds": 2,
    "totalVentilators": 11,
    "availableVentilators": 3,
    "hasVentilator": true,
    "hasTraumaSurgery": false,
    "hasBloodBank": true,
    "hasOxygenGenerator": true,
    "specialists": [
      "Trauma Surgeon"
    ]
  },
  {
    "id": "jh-community-health-centre-chc-block-1-ranchi",
    "name": "Community Health Centre (CHC) Block 1 - Ranchi",
    "shortCode": "CHCBR",
    "districtName": "Ranchi",
    "facilityTier": "CHC",
    "latitude": 23.388,
    "longitude": 85.446,
    "totalGeneralBeds": 70,
    "availableGeneralBeds": 31,
    "totalIcuBeds": 4,
    "availableIcuBeds": 1,
    "totalVentilators": 0,
    "availableVentilators": 0,
    "hasVentilator": false,
    "hasTraumaSurgery": false,
    "hasBloodBank": false,
    "hasOxygenGenerator": true,
    "specialists": []
  },
  {
    "id": "jh-community-health-centre-chc-block-2-ranchi",
    "name": "Community Health Centre (CHC) Block 2 - Ranchi",
    "shortCode": "CHCBR",
    "districtName": "Ranchi",
    "facilityTier": "CHC",
    "latitude": 23.2636,
    "longitude": 85.198,
    "totalGeneralBeds": 43,
    "availableGeneralBeds": 8,
    "totalIcuBeds": 6,
    "availableIcuBeds": 1,
    "totalVentilators": 4,
    "availableVentilators": 1,
    "hasVentilator": true,
    "hasTraumaSurgery": false,
    "hasBloodBank": false,
    "hasOxygenGenerator": true,
    "specialists": []
  },
  {
    "id": "jh-sadar-district-hospital-east",
    "name": "Sadar District Hospital East",
    "shortCode": "SDHE",
    "districtName": "East Singhbhum (Jamshedpur)",
    "facilityTier": "DISTRICT",
    "latitude": 22.8153,
    "longitude": 86.1975,
    "totalGeneralBeds": 186,
    "availableGeneralBeds": 57,
    "totalIcuBeds": 29,
    "availableIcuBeds": 5,
    "totalVentilators": 17,
    "availableVentilators": 4,
    "hasVentilator": true,
    "hasTraumaSurgery": true,
    "hasBloodBank": true,
    "hasOxygenGenerator": true,
    "specialists": [
      "Pulmonologist"
    ]
  },
  {
    "id": "jh-community-health-centre-chc-block-1-east",
    "name": "Community Health Centre (CHC) Block 1 - East",
    "shortCode": "CHCBE",
    "districtName": "East Singhbhum (Jamshedpur)",
    "facilityTier": "CHC",
    "latitude": 22.897,
    "longitude": 86.0646,
    "totalGeneralBeds": 35,
    "availableGeneralBeds": 12,
    "totalIcuBeds": 3,
    "availableIcuBeds": 1,
    "totalVentilators": 2,
    "availableVentilators": 1,
    "hasVentilator": true,
    "hasTraumaSurgery": false,
    "hasBloodBank": false,
    "hasOxygenGenerator": true,
    "specialists": []
  },
  {
    "id": "jh-community-health-centre-chc-block-2-east",
    "name": "Community Health Centre (CHC) Block 2 - East",
    "shortCode": "CHCBE",
    "districtName": "East Singhbhum (Jamshedpur)",
    "facilityTier": "CHC",
    "latitude": 22.8953,
    "longitude": 86.0695,
    "totalGeneralBeds": 71,
    "availableGeneralBeds": 15,
    "totalIcuBeds": 5,
    "availableIcuBeds": 1,
    "totalVentilators": 3,
    "availableVentilators": 1,
    "hasVentilator": true,
    "hasTraumaSurgery": false,
    "hasBloodBank": false,
    "hasOxygenGenerator": false,
    "specialists": []
  },
  {
    "id": "jh-sadar-district-hospital-dhanbad",
    "name": "Sadar District Hospital Dhanbad",
    "shortCode": "SDHD",
    "districtName": "Dhanbad",
    "facilityTier": "DISTRICT",
    "latitude": 23.7762,
    "longitude": 86.4421,
    "totalGeneralBeds": 158,
    "availableGeneralBeds": 47,
    "totalIcuBeds": 24,
    "availableIcuBeds": 5,
    "totalVentilators": 14,
    "availableVentilators": 4,
    "hasVentilator": true,
    "hasTraumaSurgery": false,
    "hasBloodBank": true,
    "hasOxygenGenerator": true,
    "specialists": [
      "Pulmonologist"
    ]
  },
  {
    "id": "jh-community-health-centre-chc-block-1-dhanbad",
    "name": "Community Health Centre (CHC) Block 1 - Dhanbad",
    "shortCode": "CHCBD",
    "districtName": "Dhanbad",
    "facilityTier": "CHC",
    "latitude": 23.7332,
    "longitude": 86.3486,
    "totalGeneralBeds": 57,
    "availableGeneralBeds": 14,
    "totalIcuBeds": 7,
    "availableIcuBeds": 1,
    "totalVentilators": 4,
    "availableVentilators": 1,
    "hasVentilator": true,
    "hasTraumaSurgery": false,
    "hasBloodBank": false,
    "hasOxygenGenerator": false,
    "specialists": []
  },
  {
    "id": "jh-community-health-centre-chc-block-2-dhanbad",
    "name": "Community Health Centre (CHC) Block 2 - Dhanbad",
    "shortCode": "CHCBD",
    "districtName": "Dhanbad",
    "facilityTier": "CHC",
    "latitude": 23.94,
    "longitude": 86.4004,
    "totalGeneralBeds": 50,
    "availableGeneralBeds": 19,
    "totalIcuBeds": 3,
    "availableIcuBeds": 1,
    "totalVentilators": 0,
    "availableVentilators": 0,
    "hasVentilator": false,
    "hasTraumaSurgery": false,
    "hasBloodBank": false,
    "hasOxygenGenerator": false,
    "specialists": []
  },
  {
    "id": "jh-sadar-district-hospital-bokaro",
    "name": "Sadar District Hospital Bokaro",
    "shortCode": "SDHB",
    "districtName": "Bokaro",
    "facilityTier": "DISTRICT",
    "latitude": 23.6689,
    "longitude": 86.1475,
    "totalGeneralBeds": 260,
    "availableGeneralBeds": 68,
    "totalIcuBeds": 19,
    "availableIcuBeds": 3,
    "totalVentilators": 11,
    "availableVentilators": 3,
    "hasVentilator": true,
    "hasTraumaSurgery": false,
    "hasBloodBank": true,
    "hasOxygenGenerator": true,
    "specialists": [
      "Cardiologist"
    ]
  },
  {
    "id": "jh-community-health-centre-chc-block-1-bokaro",
    "name": "Community Health Centre (CHC) Block 1 - Bokaro",
    "shortCode": "CHCBB",
    "districtName": "Bokaro",
    "facilityTier": "CHC",
    "latitude": 23.5792,
    "longitude": 86.1158,
    "totalGeneralBeds": 44,
    "availableGeneralBeds": 15,
    "totalIcuBeds": 7,
    "availableIcuBeds": 1,
    "totalVentilators": 0,
    "availableVentilators": 0,
    "hasVentilator": false,
    "hasTraumaSurgery": false,
    "hasBloodBank": false,
    "hasOxygenGenerator": false,
    "specialists": []
  },
  {
    "id": "jh-community-health-centre-chc-block-2-bokaro",
    "name": "Community Health Centre (CHC) Block 2 - Bokaro",
    "shortCode": "CHCBB",
    "districtName": "Bokaro",
    "facilityTier": "CHC",
    "latitude": 23.5571,
    "longitude": 86.1242,
    "totalGeneralBeds": 33,
    "availableGeneralBeds": 16,
    "totalIcuBeds": 7,
    "availableIcuBeds": 1,
    "totalVentilators": 0,
    "availableVentilators": 0,
    "hasVentilator": false,
    "hasTraumaSurgery": false,
    "hasBloodBank": false,
    "hasOxygenGenerator": true,
    "specialists": []
  },
  {
    "id": "jh-sadar-district-hospital-hazaribagh",
    "name": "Sadar District Hospital Hazaribagh",
    "shortCode": "SDHH",
    "districtName": "Hazaribagh",
    "facilityTier": "DISTRICT",
    "latitude": 23.9819,
    "longitude": 85.3816,
    "totalGeneralBeds": 191,
    "availableGeneralBeds": 39,
    "totalIcuBeds": 27,
    "availableIcuBeds": 6,
    "totalVentilators": 16,
    "availableVentilators": 4,
    "hasVentilator": true,
    "hasTraumaSurgery": true,
    "hasBloodBank": true,
    "hasOxygenGenerator": true,
    "specialists": [
      "Trauma Surgeon"
    ]
  },
  {
    "id": "jh-community-health-centre-chc-block-1-hazaribagh",
    "name": "Community Health Centre (CHC) Block 1 - Hazaribagh",
    "shortCode": "CHCBH",
    "districtName": "Hazaribagh",
    "facilityTier": "CHC",
    "latitude": 23.926,
    "longitude": 85.5114,
    "totalGeneralBeds": 51,
    "availableGeneralBeds": 24,
    "totalIcuBeds": 5,
    "availableIcuBeds": 1,
    "totalVentilators": 3,
    "availableVentilators": 1,
    "hasVentilator": true,
    "hasTraumaSurgery": false,
    "hasBloodBank": false,
    "hasOxygenGenerator": true,
    "specialists": []
  },
  {
    "id": "jh-community-health-centre-chc-block-2-hazaribagh",
    "name": "Community Health Centre (CHC) Block 2 - Hazaribagh",
    "shortCode": "CHCBH",
    "districtName": "Hazaribagh",
    "facilityTier": "CHC",
    "latitude": 23.9873,
    "longitude": 85.4993,
    "totalGeneralBeds": 61,
    "availableGeneralBeds": 23,
    "totalIcuBeds": 6,
    "availableIcuBeds": 1,
    "totalVentilators": 0,
    "availableVentilators": 0,
    "hasVentilator": false,
    "hasTraumaSurgery": false,
    "hasBloodBank": false,
    "hasOxygenGenerator": true,
    "specialists": []
  },
  {
    "id": "jh-sadar-district-hospital-palamu",
    "name": "Sadar District Hospital Palamu",
    "shortCode": "SDHP",
    "districtName": "Palamu (Daltonganj)",
    "facilityTier": "DISTRICT",
    "latitude": 24.0339,
    "longitude": 84.0563,
    "totalGeneralBeds": 150,
    "availableGeneralBeds": 25,
    "totalIcuBeds": 26,
    "availableIcuBeds": 6,
    "totalVentilators": 16,
    "availableVentilators": 4,
    "hasVentilator": true,
    "hasTraumaSurgery": false,
    "hasBloodBank": true,
    "hasOxygenGenerator": true,
    "specialists": [
      "Pulmonologist",
      "Trauma Surgeon"
    ]
  },
  {
    "id": "jh-community-health-centre-chc-block-1-palamu",
    "name": "Community Health Centre (CHC) Block 1 - Palamu",
    "shortCode": "CHCBP",
    "districtName": "Palamu (Daltonganj)",
    "facilityTier": "CHC",
    "latitude": 24.1686,
    "longitude": 84.0513,
    "totalGeneralBeds": 50,
    "availableGeneralBeds": 13,
    "totalIcuBeds": 6,
    "availableIcuBeds": 1,
    "totalVentilators": 0,
    "availableVentilators": 0,
    "hasVentilator": false,
    "hasTraumaSurgery": false,
    "hasBloodBank": false,
    "hasOxygenGenerator": true,
    "specialists": []
  },
  {
    "id": "jh-community-health-centre-chc-block-2-palamu",
    "name": "Community Health Centre (CHC) Block 2 - Palamu",
    "shortCode": "CHCBP",
    "districtName": "Palamu (Daltonganj)",
    "facilityTier": "CHC",
    "latitude": 24.0674,
    "longitude": 84.1035,
    "totalGeneralBeds": 52,
    "availableGeneralBeds": 19,
    "totalIcuBeds": 6,
    "availableIcuBeds": 1,
    "totalVentilators": 4,
    "availableVentilators": 1,
    "hasVentilator": true,
    "hasTraumaSurgery": false,
    "hasBloodBank": false,
    "hasOxygenGenerator": false,
    "specialists": []
  },
  {
    "id": "jh-sadar-district-hospital-deoghar",
    "name": "Sadar District Hospital Deoghar",
    "shortCode": "SDHD",
    "districtName": "Deoghar",
    "facilityTier": "DISTRICT",
    "latitude": 24.483,
    "longitude": 86.7038,
    "totalGeneralBeds": 191,
    "availableGeneralBeds": 32,
    "totalIcuBeds": 24,
    "availableIcuBeds": 3,
    "totalVentilators": 14,
    "availableVentilators": 4,
    "hasVentilator": true,
    "hasTraumaSurgery": false,
    "hasBloodBank": true,
    "hasOxygenGenerator": true,
    "specialists": [
      "Pulmonologist"
    ]
  },
  {
    "id": "jh-community-health-centre-chc-block-1-deoghar",
    "name": "Community Health Centre (CHC) Block 1 - Deoghar",
    "shortCode": "CHCBD",
    "districtName": "Deoghar",
    "facilityTier": "CHC",
    "latitude": 24.3498,
    "longitude": 86.552,
    "totalGeneralBeds": 67,
    "availableGeneralBeds": 17,
    "totalIcuBeds": 2,
    "availableIcuBeds": 0,
    "totalVentilators": 0,
    "availableVentilators": 0,
    "hasVentilator": false,
    "hasTraumaSurgery": false,
    "hasBloodBank": false,
    "hasOxygenGenerator": false,
    "specialists": []
  },
  {
    "id": "jh-community-health-centre-chc-block-2-deoghar",
    "name": "Community Health Centre (CHC) Block 2 - Deoghar",
    "shortCode": "CHCBD",
    "districtName": "Deoghar",
    "facilityTier": "CHC",
    "latitude": 24.5052,
    "longitude": 86.6047,
    "totalGeneralBeds": 63,
    "availableGeneralBeds": 24,
    "totalIcuBeds": 3,
    "availableIcuBeds": 1,
    "totalVentilators": 0,
    "availableVentilators": 0,
    "hasVentilator": false,
    "hasTraumaSurgery": false,
    "hasBloodBank": false,
    "hasOxygenGenerator": true,
    "specialists": []
  },
  {
    "id": "jh-sadar-district-hospital-giridih",
    "name": "Sadar District Hospital Giridih",
    "shortCode": "SDHG",
    "districtName": "Giridih",
    "facilityTier": "DISTRICT",
    "latitude": 24.1912,
    "longitude": 86.3141,
    "totalGeneralBeds": 270,
    "availableGeneralBeds": 46,
    "totalIcuBeds": 22,
    "availableIcuBeds": 3,
    "totalVentilators": 13,
    "availableVentilators": 3,
    "hasVentilator": true,
    "hasTraumaSurgery": true,
    "hasBloodBank": true,
    "hasOxygenGenerator": true,
    "specialists": [
      "Trauma Surgeon"
    ]
  },
  {
    "id": "jh-community-health-centre-chc-block-1-giridih",
    "name": "Community Health Centre (CHC) Block 1 - Giridih",
    "shortCode": "CHCBG",
    "districtName": "Giridih",
    "facilityTier": "CHC",
    "latitude": 24.2157,
    "longitude": 86.3026,
    "totalGeneralBeds": 70,
    "availableGeneralBeds": 32,
    "totalIcuBeds": 8,
    "availableIcuBeds": 2,
    "totalVentilators": 5,
    "availableVentilators": 1,
    "hasVentilator": true,
    "hasTraumaSurgery": false,
    "hasBloodBank": false,
    "hasOxygenGenerator": true,
    "specialists": []
  },
  {
    "id": "jh-community-health-centre-chc-block-2-giridih",
    "name": "Community Health Centre (CHC) Block 2 - Giridih",
    "shortCode": "CHCBG",
    "districtName": "Giridih",
    "facilityTier": "CHC",
    "latitude": 24.1694,
    "longitude": 86.3044,
    "totalGeneralBeds": 75,
    "availableGeneralBeds": 25,
    "totalIcuBeds": 3,
    "availableIcuBeds": 1,
    "totalVentilators": 2,
    "availableVentilators": 1,
    "hasVentilator": true,
    "hasTraumaSurgery": false,
    "hasBloodBank": false,
    "hasOxygenGenerator": false,
    "specialists": []
  },
  {
    "id": "jh-sadar-district-hospital-dumka",
    "name": "Sadar District Hospital Dumka",
    "shortCode": "SDHD",
    "districtName": "Dumka",
    "facilityTier": "DISTRICT",
    "latitude": 24.258,
    "longitude": 87.2319,
    "totalGeneralBeds": 258,
    "availableGeneralBeds": 40,
    "totalIcuBeds": 22,
    "availableIcuBeds": 4,
    "totalVentilators": 13,
    "availableVentilators": 3,
    "hasVentilator": true,
    "hasTraumaSurgery": false,
    "hasBloodBank": true,
    "hasOxygenGenerator": true,
    "specialists": [
      "Trauma Surgeon"
    ]
  },
  {
    "id": "jh-community-health-centre-chc-block-1-dumka",
    "name": "Community Health Centre (CHC) Block 1 - Dumka",
    "shortCode": "CHCBD",
    "districtName": "Dumka",
    "facilityTier": "CHC",
    "latitude": 24.4,
    "longitude": 87.2002,
    "totalGeneralBeds": 40,
    "availableGeneralBeds": 14,
    "totalIcuBeds": 7,
    "availableIcuBeds": 1,
    "totalVentilators": 0,
    "availableVentilators": 0,
    "hasVentilator": false,
    "hasTraumaSurgery": false,
    "hasBloodBank": false,
    "hasOxygenGenerator": false,
    "specialists": []
  },
  {
    "id": "jh-community-health-centre-chc-block-2-dumka",
    "name": "Community Health Centre (CHC) Block 2 - Dumka",
    "shortCode": "CHCBD",
    "districtName": "Dumka",
    "facilityTier": "CHC",
    "latitude": 24.1599,
    "longitude": 87.1309,
    "totalGeneralBeds": 48,
    "availableGeneralBeds": 17,
    "totalIcuBeds": 6,
    "availableIcuBeds": 2,
    "totalVentilators": 4,
    "availableVentilators": 1,
    "hasVentilator": true,
    "hasTraumaSurgery": false,
    "hasBloodBank": false,
    "hasOxygenGenerator": false,
    "specialists": []
  },
  {
    "id": "jh-sadar-district-hospital-ramgarh",
    "name": "Sadar District Hospital Ramgarh",
    "shortCode": "SDHR",
    "districtName": "Ramgarh",
    "facilityTier": "DISTRICT",
    "latitude": 23.6346,
    "longitude": 85.5289,
    "totalGeneralBeds": 227,
    "availableGeneralBeds": 54,
    "totalIcuBeds": 29,
    "availableIcuBeds": 5,
    "totalVentilators": 17,
    "availableVentilators": 4,
    "hasVentilator": true,
    "hasTraumaSurgery": true,
    "hasBloodBank": true,
    "hasOxygenGenerator": true,
    "specialists": [
      "Cardiologist"
    ]
  },
  {
    "id": "jh-community-health-centre-chc-block-1-ramgarh",
    "name": "Community Health Centre (CHC) Block 1 - Ramgarh",
    "shortCode": "CHCBR",
    "districtName": "Ramgarh",
    "facilityTier": "CHC",
    "latitude": 23.7044,
    "longitude": 85.5482,
    "totalGeneralBeds": 48,
    "availableGeneralBeds": 20,
    "totalIcuBeds": 8,
    "availableIcuBeds": 2,
    "totalVentilators": 5,
    "availableVentilators": 1,
    "hasVentilator": true,
    "hasTraumaSurgery": false,
    "hasBloodBank": false,
    "hasOxygenGenerator": false,
    "specialists": []
  },
  {
    "id": "jh-community-health-centre-chc-block-2-ramgarh",
    "name": "Community Health Centre (CHC) Block 2 - Ramgarh",
    "shortCode": "CHCBR",
    "districtName": "Ramgarh",
    "facilityTier": "CHC",
    "latitude": 23.6863,
    "longitude": 85.4083,
    "totalGeneralBeds": 38,
    "availableGeneralBeds": 16,
    "totalIcuBeds": 5,
    "availableIcuBeds": 1,
    "totalVentilators": 3,
    "availableVentilators": 1,
    "hasVentilator": true,
    "hasTraumaSurgery": false,
    "hasBloodBank": false,
    "hasOxygenGenerator": false,
    "specialists": []
  },
  {
    "id": "jh-sadar-district-hospital-west",
    "name": "Sadar District Hospital West",
    "shortCode": "SDHW",
    "districtName": "West Singhbhum (Chaibasa)",
    "facilityTier": "DISTRICT",
    "latitude": 22.5687,
    "longitude": 85.7895,
    "totalGeneralBeds": 162,
    "availableGeneralBeds": 49,
    "totalIcuBeds": 30,
    "availableIcuBeds": 3,
    "totalVentilators": 18,
    "availableVentilators": 5,
    "hasVentilator": true,
    "hasTraumaSurgery": false,
    "hasBloodBank": true,
    "hasOxygenGenerator": true,
    "specialists": [
      "Trauma Surgeon",
      "Pulmonologist"
    ]
  },
  {
    "id": "jh-community-health-centre-chc-block-1-west",
    "name": "Community Health Centre (CHC) Block 1 - West",
    "shortCode": "CHCBW",
    "districtName": "West Singhbhum (Chaibasa)",
    "facilityTier": "CHC",
    "latitude": 22.6314,
    "longitude": 85.6852,
    "totalGeneralBeds": 77,
    "availableGeneralBeds": 29,
    "totalIcuBeds": 7,
    "availableIcuBeds": 1,
    "totalVentilators": 4,
    "availableVentilators": 1,
    "hasVentilator": true,
    "hasTraumaSurgery": false,
    "hasBloodBank": false,
    "hasOxygenGenerator": false,
    "specialists": []
  },
  {
    "id": "jh-community-health-centre-chc-block-2-west",
    "name": "Community Health Centre (CHC) Block 2 - West",
    "shortCode": "CHCBW",
    "districtName": "West Singhbhum (Chaibasa)",
    "facilityTier": "CHC",
    "latitude": 22.6397,
    "longitude": 85.8907,
    "totalGeneralBeds": 67,
    "availableGeneralBeds": 23,
    "totalIcuBeds": 8,
    "availableIcuBeds": 2,
    "totalVentilators": 5,
    "availableVentilators": 1,
    "hasVentilator": true,
    "hasTraumaSurgery": false,
    "hasBloodBank": false,
    "hasOxygenGenerator": true,
    "specialists": []
  },
  {
    "id": "jh-sadar-district-hospital-koderma",
    "name": "Sadar District Hospital Koderma",
    "shortCode": "SDHK",
    "districtName": "Koderma",
    "facilityTier": "DISTRICT",
    "latitude": 24.4585,
    "longitude": 85.5958,
    "totalGeneralBeds": 177,
    "availableGeneralBeds": 46,
    "totalIcuBeds": 24,
    "availableIcuBeds": 5,
    "totalVentilators": 14,
    "availableVentilators": 4,
    "hasVentilator": true,
    "hasTraumaSurgery": false,
    "hasBloodBank": true,
    "hasOxygenGenerator": true,
    "specialists": [
      "Pulmonologist",
      "Trauma Surgeon"
    ]
  },
  {
    "id": "jh-community-health-centre-chc-block-1-koderma",
    "name": "Community Health Centre (CHC) Block 1 - Koderma",
    "shortCode": "CHCBK",
    "districtName": "Koderma",
    "facilityTier": "CHC",
    "latitude": 24.4143,
    "longitude": 85.459,
    "totalGeneralBeds": 41,
    "availableGeneralBeds": 18,
    "totalIcuBeds": 5,
    "availableIcuBeds": 1,
    "totalVentilators": 0,
    "availableVentilators": 0,
    "hasVentilator": false,
    "hasTraumaSurgery": false,
    "hasBloodBank": false,
    "hasOxygenGenerator": true,
    "specialists": []
  },
  {
    "id": "jh-community-health-centre-chc-block-2-koderma",
    "name": "Community Health Centre (CHC) Block 2 - Koderma",
    "shortCode": "CHCBK",
    "districtName": "Koderma",
    "facilityTier": "CHC",
    "latitude": 24.5749,
    "longitude": 85.667,
    "totalGeneralBeds": 59,
    "availableGeneralBeds": 17,
    "totalIcuBeds": 5,
    "availableIcuBeds": 1,
    "totalVentilators": 3,
    "availableVentilators": 1,
    "hasVentilator": true,
    "hasTraumaSurgery": false,
    "hasBloodBank": false,
    "hasOxygenGenerator": false,
    "specialists": []
  },
  {
    "id": "jh-sadar-district-hospital-chatra",
    "name": "Sadar District Hospital Chatra",
    "shortCode": "SDHC",
    "districtName": "Chatra",
    "facilityTier": "DISTRICT",
    "latitude": 24.1985,
    "longitude": 84.8782,
    "totalGeneralBeds": 172,
    "availableGeneralBeds": 46,
    "totalIcuBeds": 27,
    "availableIcuBeds": 1,
    "totalVentilators": 16,
    "availableVentilators": 4,
    "hasVentilator": true,
    "hasTraumaSurgery": false,
    "hasBloodBank": true,
    "hasOxygenGenerator": true,
    "specialists": [
      "Pulmonologist"
    ]
  },
  {
    "id": "jh-community-health-centre-chc-block-1-chatra",
    "name": "Community Health Centre (CHC) Block 1 - Chatra",
    "shortCode": "CHCBC",
    "districtName": "Chatra",
    "facilityTier": "CHC",
    "latitude": 24.1879,
    "longitude": 84.8707,
    "totalGeneralBeds": 77,
    "availableGeneralBeds": 17,
    "totalIcuBeds": 5,
    "availableIcuBeds": 1,
    "totalVentilators": 3,
    "availableVentilators": 1,
    "hasVentilator": true,
    "hasTraumaSurgery": false,
    "hasBloodBank": false,
    "hasOxygenGenerator": false,
    "specialists": []
  },
  {
    "id": "jh-community-health-centre-chc-block-2-chatra",
    "name": "Community Health Centre (CHC) Block 2 - Chatra",
    "shortCode": "CHCBC",
    "districtName": "Chatra",
    "facilityTier": "CHC",
    "latitude": 24.3065,
    "longitude": 84.89,
    "totalGeneralBeds": 76,
    "availableGeneralBeds": 34,
    "totalIcuBeds": 5,
    "availableIcuBeds": 1,
    "totalVentilators": 3,
    "availableVentilators": 1,
    "hasVentilator": true,
    "hasTraumaSurgery": false,
    "hasBloodBank": false,
    "hasOxygenGenerator": true,
    "specialists": []
  },
  {
    "id": "jh-sadar-district-hospital-garhwa",
    "name": "Sadar District Hospital Garhwa",
    "shortCode": "SDHG",
    "districtName": "Garhwa",
    "facilityTier": "DISTRICT",
    "latitude": 24.1626,
    "longitude": 83.8126,
    "totalGeneralBeds": 181,
    "availableGeneralBeds": 50,
    "totalIcuBeds": 22,
    "availableIcuBeds": 3,
    "totalVentilators": 13,
    "availableVentilators": 3,
    "hasVentilator": true,
    "hasTraumaSurgery": false,
    "hasBloodBank": true,
    "hasOxygenGenerator": true,
    "specialists": [
      "Trauma Surgeon"
    ]
  },
  {
    "id": "jh-community-health-centre-chc-block-1-garhwa",
    "name": "Community Health Centre (CHC) Block 1 - Garhwa",
    "shortCode": "CHCBG",
    "districtName": "Garhwa",
    "facilityTier": "CHC",
    "latitude": 24.2304,
    "longitude": 83.85,
    "totalGeneralBeds": 61,
    "availableGeneralBeds": 29,
    "totalIcuBeds": 5,
    "availableIcuBeds": 1,
    "totalVentilators": 0,
    "availableVentilators": 0,
    "hasVentilator": false,
    "hasTraumaSurgery": false,
    "hasBloodBank": false,
    "hasOxygenGenerator": true,
    "specialists": []
  },
  {
    "id": "jh-community-health-centre-chc-block-2-garhwa",
    "name": "Community Health Centre (CHC) Block 2 - Garhwa",
    "shortCode": "CHCBG",
    "districtName": "Garhwa",
    "facilityTier": "CHC",
    "latitude": 24.0899,
    "longitude": 83.8393,
    "totalGeneralBeds": 31,
    "availableGeneralBeds": 11,
    "totalIcuBeds": 7,
    "availableIcuBeds": 1,
    "totalVentilators": 0,
    "availableVentilators": 0,
    "hasVentilator": false,
    "hasTraumaSurgery": false,
    "hasBloodBank": false,
    "hasOxygenGenerator": true,
    "specialists": []
  },
  {
    "id": "jh-sadar-district-hospital-latehar",
    "name": "Sadar District Hospital Latehar",
    "shortCode": "SDHL",
    "districtName": "Latehar",
    "facilityTier": "DISTRICT",
    "latitude": 23.7297,
    "longitude": 84.4931,
    "totalGeneralBeds": 207,
    "availableGeneralBeds": 31,
    "totalIcuBeds": 17,
    "availableIcuBeds": 1,
    "totalVentilators": 10,
    "availableVentilators": 3,
    "hasVentilator": true,
    "hasTraumaSurgery": false,
    "hasBloodBank": true,
    "hasOxygenGenerator": true,
    "specialists": [
      "Trauma Surgeon"
    ]
  },
  {
    "id": "jh-community-health-centre-chc-block-1-latehar",
    "name": "Community Health Centre (CHC) Block 1 - Latehar",
    "shortCode": "CHCBL",
    "districtName": "Latehar",
    "facilityTier": "CHC",
    "latitude": 23.7137,
    "longitude": 84.4813,
    "totalGeneralBeds": 41,
    "availableGeneralBeds": 11,
    "totalIcuBeds": 8,
    "availableIcuBeds": 1,
    "totalVentilators": 0,
    "availableVentilators": 0,
    "hasVentilator": false,
    "hasTraumaSurgery": false,
    "hasBloodBank": false,
    "hasOxygenGenerator": false,
    "specialists": []
  },
  {
    "id": "jh-community-health-centre-chc-block-2-latehar",
    "name": "Community Health Centre (CHC) Block 2 - Latehar",
    "shortCode": "CHCBL",
    "districtName": "Latehar",
    "facilityTier": "CHC",
    "latitude": 23.7153,
    "longitude": 84.5717,
    "totalGeneralBeds": 76,
    "availableGeneralBeds": 37,
    "totalIcuBeds": 8,
    "availableIcuBeds": 2,
    "totalVentilators": 5,
    "availableVentilators": 1,
    "hasVentilator": true,
    "hasTraumaSurgery": false,
    "hasBloodBank": false,
    "hasOxygenGenerator": false,
    "specialists": []
  },
  {
    "id": "jh-sadar-district-hospital-lohardaga",
    "name": "Sadar District Hospital Lohardaga",
    "shortCode": "SDHL",
    "districtName": "Lohardaga",
    "facilityTier": "DISTRICT",
    "latitude": 23.4385,
    "longitude": 84.6969,
    "totalGeneralBeds": 165,
    "availableGeneralBeds": 59,
    "totalIcuBeds": 17,
    "availableIcuBeds": 3,
    "totalVentilators": 10,
    "availableVentilators": 3,
    "hasVentilator": true,
    "hasTraumaSurgery": false,
    "hasBloodBank": true,
    "hasOxygenGenerator": true,
    "specialists": [
      "Trauma Surgeon"
    ]
  },
  {
    "id": "jh-community-health-centre-chc-block-1-lohardaga",
    "name": "Community Health Centre (CHC) Block 1 - Lohardaga",
    "shortCode": "CHCBL",
    "districtName": "Lohardaga",
    "facilityTier": "CHC",
    "latitude": 23.5818,
    "longitude": 84.7379,
    "totalGeneralBeds": 33,
    "availableGeneralBeds": 12,
    "totalIcuBeds": 5,
    "availableIcuBeds": 1,
    "totalVentilators": 3,
    "availableVentilators": 1,
    "hasVentilator": true,
    "hasTraumaSurgery": false,
    "hasBloodBank": false,
    "hasOxygenGenerator": true,
    "specialists": []
  },
  {
    "id": "jh-community-health-centre-chc-block-2-lohardaga",
    "name": "Community Health Centre (CHC) Block 2 - Lohardaga",
    "shortCode": "CHCBL",
    "districtName": "Lohardaga",
    "facilityTier": "CHC",
    "latitude": 23.4072,
    "longitude": 84.8137,
    "totalGeneralBeds": 40,
    "availableGeneralBeds": 15,
    "totalIcuBeds": 6,
    "availableIcuBeds": 1,
    "totalVentilators": 0,
    "availableVentilators": 0,
    "hasVentilator": false,
    "hasTraumaSurgery": false,
    "hasBloodBank": false,
    "hasOxygenGenerator": false,
    "specialists": []
  },
  {
    "id": "jh-sadar-district-hospital-gumla",
    "name": "Sadar District Hospital Gumla",
    "shortCode": "SDHG",
    "districtName": "Gumla",
    "facilityTier": "DISTRICT",
    "latitude": 23.0006,
    "longitude": 84.5394,
    "totalGeneralBeds": 262,
    "availableGeneralBeds": 57,
    "totalIcuBeds": 15,
    "availableIcuBeds": 1,
    "totalVentilators": 9,
    "availableVentilators": 2,
    "hasVentilator": true,
    "hasTraumaSurgery": false,
    "hasBloodBank": true,
    "hasOxygenGenerator": true,
    "specialists": [
      "Cardiologist"
    ]
  },
  {
    "id": "jh-community-health-centre-chc-block-1-gumla",
    "name": "Community Health Centre (CHC) Block 1 - Gumla",
    "shortCode": "CHCBG",
    "districtName": "Gumla",
    "facilityTier": "CHC",
    "latitude": 23.1378,
    "longitude": 84.6412,
    "totalGeneralBeds": 74,
    "availableGeneralBeds": 18,
    "totalIcuBeds": 8,
    "availableIcuBeds": 1,
    "totalVentilators": 0,
    "availableVentilators": 0,
    "hasVentilator": false,
    "hasTraumaSurgery": false,
    "hasBloodBank": false,
    "hasOxygenGenerator": false,
    "specialists": []
  },
  {
    "id": "jh-community-health-centre-chc-block-2-gumla",
    "name": "Community Health Centre (CHC) Block 2 - Gumla",
    "shortCode": "CHCBG",
    "districtName": "Gumla",
    "facilityTier": "CHC",
    "latitude": 23.1433,
    "longitude": 84.4919,
    "totalGeneralBeds": 45,
    "availableGeneralBeds": 10,
    "totalIcuBeds": 5,
    "availableIcuBeds": 1,
    "totalVentilators": 3,
    "availableVentilators": 1,
    "hasVentilator": true,
    "hasTraumaSurgery": false,
    "hasBloodBank": false,
    "hasOxygenGenerator": true,
    "specialists": []
  },
  {
    "id": "jh-sadar-district-hospital-simdega",
    "name": "Sadar District Hospital Simdega",
    "shortCode": "SDHS",
    "districtName": "Simdega",
    "facilityTier": "DISTRICT",
    "latitude": 22.6329,
    "longitude": 84.5148,
    "totalGeneralBeds": 160,
    "availableGeneralBeds": 26,
    "totalIcuBeds": 19,
    "availableIcuBeds": 1,
    "totalVentilators": 11,
    "availableVentilators": 3,
    "hasVentilator": true,
    "hasTraumaSurgery": false,
    "hasBloodBank": true,
    "hasOxygenGenerator": true,
    "specialists": [
      "Cardiologist"
    ]
  },
  {
    "id": "jh-community-health-centre-chc-block-1-simdega",
    "name": "Community Health Centre (CHC) Block 1 - Simdega",
    "shortCode": "CHCBS",
    "districtName": "Simdega",
    "facilityTier": "CHC",
    "latitude": 22.5465,
    "longitude": 84.5011,
    "totalGeneralBeds": 65,
    "availableGeneralBeds": 25,
    "totalIcuBeds": 2,
    "availableIcuBeds": 0,
    "totalVentilators": 0,
    "availableVentilators": 0,
    "hasVentilator": false,
    "hasTraumaSurgery": false,
    "hasBloodBank": false,
    "hasOxygenGenerator": false,
    "specialists": []
  },
  {
    "id": "jh-community-health-centre-chc-block-2-simdega",
    "name": "Community Health Centre (CHC) Block 2 - Simdega",
    "shortCode": "CHCBS",
    "districtName": "Simdega",
    "facilityTier": "CHC",
    "latitude": 22.6496,
    "longitude": 84.3927,
    "totalGeneralBeds": 39,
    "availableGeneralBeds": 12,
    "totalIcuBeds": 6,
    "availableIcuBeds": 1,
    "totalVentilators": 0,
    "availableVentilators": 0,
    "hasVentilator": false,
    "hasTraumaSurgery": false,
    "hasBloodBank": false,
    "hasOxygenGenerator": false,
    "specialists": []
  },
  {
    "id": "jh-sadar-district-hospital-khunti",
    "name": "Sadar District Hospital Khunti",
    "shortCode": "SDHK",
    "districtName": "Khunti",
    "facilityTier": "DISTRICT",
    "latitude": 23.0801,
    "longitude": 85.2728,
    "totalGeneralBeds": 286,
    "availableGeneralBeds": 67,
    "totalIcuBeds": 27,
    "availableIcuBeds": 4,
    "totalVentilators": 16,
    "availableVentilators": 4,
    "hasVentilator": true,
    "hasTraumaSurgery": true,
    "hasBloodBank": true,
    "hasOxygenGenerator": true,
    "specialists": [
      "Pulmonologist",
      "Trauma Surgeon"
    ]
  },
  {
    "id": "jh-community-health-centre-chc-block-1-khunti",
    "name": "Community Health Centre (CHC) Block 1 - Khunti",
    "shortCode": "CHCBK",
    "districtName": "Khunti",
    "facilityTier": "CHC",
    "latitude": 23.1702,
    "longitude": 85.2289,
    "totalGeneralBeds": 60,
    "availableGeneralBeds": 29,
    "totalIcuBeds": 3,
    "availableIcuBeds": 1,
    "totalVentilators": 0,
    "availableVentilators": 0,
    "hasVentilator": false,
    "hasTraumaSurgery": false,
    "hasBloodBank": false,
    "hasOxygenGenerator": true,
    "specialists": []
  },
  {
    "id": "jh-community-health-centre-chc-block-2-khunti",
    "name": "Community Health Centre (CHC) Block 2 - Khunti",
    "shortCode": "CHCBK",
    "districtName": "Khunti",
    "facilityTier": "CHC",
    "latitude": 23.1246,
    "longitude": 85.394,
    "totalGeneralBeds": 39,
    "availableGeneralBeds": 10,
    "totalIcuBeds": 5,
    "availableIcuBeds": 1,
    "totalVentilators": 0,
    "availableVentilators": 0,
    "hasVentilator": false,
    "hasTraumaSurgery": false,
    "hasBloodBank": false,
    "hasOxygenGenerator": true,
    "specialists": []
  },
  {
    "id": "jh-sadar-district-hospital-seraikela",
    "name": "Sadar District Hospital Seraikela",
    "shortCode": "SDHS",
    "districtName": "Seraikela Kharsawan",
    "facilityTier": "DISTRICT",
    "latitude": 22.7133,
    "longitude": 85.9463,
    "totalGeneralBeds": 222,
    "availableGeneralBeds": 36,
    "totalIcuBeds": 27,
    "availableIcuBeds": 3,
    "totalVentilators": 16,
    "availableVentilators": 4,
    "hasVentilator": true,
    "hasTraumaSurgery": false,
    "hasBloodBank": true,
    "hasOxygenGenerator": true,
    "specialists": [
      "Pulmonologist"
    ]
  },
  {
    "id": "jh-community-health-centre-chc-block-1-seraikela",
    "name": "Community Health Centre (CHC) Block 1 - Seraikela",
    "shortCode": "CHCBS",
    "districtName": "Seraikela Kharsawan",
    "facilityTier": "CHC",
    "latitude": 22.7468,
    "longitude": 86.0157,
    "totalGeneralBeds": 45,
    "availableGeneralBeds": 13,
    "totalIcuBeds": 4,
    "availableIcuBeds": 1,
    "totalVentilators": 2,
    "availableVentilators": 1,
    "hasVentilator": true,
    "hasTraumaSurgery": false,
    "hasBloodBank": false,
    "hasOxygenGenerator": true,
    "specialists": []
  },
  {
    "id": "jh-community-health-centre-chc-block-2-seraikela",
    "name": "Community Health Centre (CHC) Block 2 - Seraikela",
    "shortCode": "CHCBS",
    "districtName": "Seraikela Kharsawan",
    "facilityTier": "CHC",
    "latitude": 22.6857,
    "longitude": 86.0034,
    "totalGeneralBeds": 73,
    "availableGeneralBeds": 15,
    "totalIcuBeds": 3,
    "availableIcuBeds": 1,
    "totalVentilators": 0,
    "availableVentilators": 0,
    "hasVentilator": false,
    "hasTraumaSurgery": false,
    "hasBloodBank": false,
    "hasOxygenGenerator": false,
    "specialists": []
  },
  {
    "id": "jh-sadar-district-hospital-jamtara",
    "name": "Sadar District Hospital Jamtara",
    "shortCode": "SDHJ",
    "districtName": "Jamtara",
    "facilityTier": "DISTRICT",
    "latitude": 23.9764,
    "longitude": 86.7996,
    "totalGeneralBeds": 194,
    "availableGeneralBeds": 50,
    "totalIcuBeds": 28,
    "availableIcuBeds": 2,
    "totalVentilators": 17,
    "availableVentilators": 4,
    "hasVentilator": true,
    "hasTraumaSurgery": false,
    "hasBloodBank": true,
    "hasOxygenGenerator": true,
    "specialists": [
      "Pulmonologist",
      "Trauma Surgeon"
    ]
  },
  {
    "id": "jh-community-health-centre-chc-block-1-jamtara",
    "name": "Community Health Centre (CHC) Block 1 - Jamtara",
    "shortCode": "CHCBJ",
    "districtName": "Jamtara",
    "facilityTier": "CHC",
    "latitude": 24.0061,
    "longitude": 86.8263,
    "totalGeneralBeds": 33,
    "availableGeneralBeds": 11,
    "totalIcuBeds": 6,
    "availableIcuBeds": 1,
    "totalVentilators": 4,
    "availableVentilators": 1,
    "hasVentilator": true,
    "hasTraumaSurgery": false,
    "hasBloodBank": false,
    "hasOxygenGenerator": true,
    "specialists": []
  },
  {
    "id": "jh-community-health-centre-chc-block-2-jamtara",
    "name": "Community Health Centre (CHC) Block 2 - Jamtara",
    "shortCode": "CHCBJ",
    "districtName": "Jamtara",
    "facilityTier": "CHC",
    "latitude": 23.8818,
    "longitude": 86.7264,
    "totalGeneralBeds": 77,
    "availableGeneralBeds": 32,
    "totalIcuBeds": 3,
    "availableIcuBeds": 1,
    "totalVentilators": 2,
    "availableVentilators": 1,
    "hasVentilator": true,
    "hasTraumaSurgery": false,
    "hasBloodBank": false,
    "hasOxygenGenerator": true,
    "specialists": []
  },
  {
    "id": "jh-sadar-district-hospital-godda",
    "name": "Sadar District Hospital Godda",
    "shortCode": "SDHG",
    "districtName": "Godda",
    "facilityTier": "DISTRICT",
    "latitude": 24.8299,
    "longitude": 87.2038,
    "totalGeneralBeds": 299,
    "availableGeneralBeds": 76,
    "totalIcuBeds": 23,
    "availableIcuBeds": 4,
    "totalVentilators": 14,
    "availableVentilators": 3,
    "hasVentilator": true,
    "hasTraumaSurgery": false,
    "hasBloodBank": true,
    "hasOxygenGenerator": true,
    "specialists": [
      "Trauma Surgeon"
    ]
  },
  {
    "id": "jh-community-health-centre-chc-block-1-godda",
    "name": "Community Health Centre (CHC) Block 1 - Godda",
    "shortCode": "CHCBG",
    "districtName": "Godda",
    "facilityTier": "CHC",
    "latitude": 24.8067,
    "longitude": 87.3548,
    "totalGeneralBeds": 69,
    "availableGeneralBeds": 18,
    "totalIcuBeds": 3,
    "availableIcuBeds": 1,
    "totalVentilators": 2,
    "availableVentilators": 1,
    "hasVentilator": true,
    "hasTraumaSurgery": false,
    "hasBloodBank": false,
    "hasOxygenGenerator": true,
    "specialists": []
  },
  {
    "id": "jh-community-health-centre-chc-block-2-godda",
    "name": "Community Health Centre (CHC) Block 2 - Godda",
    "shortCode": "CHCBG",
    "districtName": "Godda",
    "facilityTier": "CHC",
    "latitude": 24.704,
    "longitude": 87.3254,
    "totalGeneralBeds": 47,
    "availableGeneralBeds": 13,
    "totalIcuBeds": 8,
    "availableIcuBeds": 2,
    "totalVentilators": 0,
    "availableVentilators": 0,
    "hasVentilator": false,
    "hasTraumaSurgery": false,
    "hasBloodBank": false,
    "hasOxygenGenerator": true,
    "specialists": []
  },
  {
    "id": "jh-sadar-district-hospital-sahibganj",
    "name": "Sadar District Hospital Sahibganj",
    "shortCode": "SDHS",
    "districtName": "Sahibganj",
    "facilityTier": "DISTRICT",
    "latitude": 25.2489,
    "longitude": 87.6503,
    "totalGeneralBeds": 183,
    "availableGeneralBeds": 53,
    "totalIcuBeds": 26,
    "availableIcuBeds": 2,
    "totalVentilators": 16,
    "availableVentilators": 4,
    "hasVentilator": true,
    "hasTraumaSurgery": false,
    "hasBloodBank": true,
    "hasOxygenGenerator": true,
    "specialists": [
      "Trauma Surgeon"
    ]
  },
  {
    "id": "jh-community-health-centre-chc-block-1-sahibganj",
    "name": "Community Health Centre (CHC) Block 1 - Sahibganj",
    "shortCode": "CHCBS",
    "districtName": "Sahibganj",
    "facilityTier": "CHC",
    "latitude": 25.1509,
    "longitude": 87.6592,
    "totalGeneralBeds": 46,
    "availableGeneralBeds": 19,
    "totalIcuBeds": 5,
    "availableIcuBeds": 1,
    "totalVentilators": 3,
    "availableVentilators": 1,
    "hasVentilator": true,
    "hasTraumaSurgery": false,
    "hasBloodBank": false,
    "hasOxygenGenerator": true,
    "specialists": []
  },
  {
    "id": "jh-community-health-centre-chc-block-2-sahibganj",
    "name": "Community Health Centre (CHC) Block 2 - Sahibganj",
    "shortCode": "CHCBS",
    "districtName": "Sahibganj",
    "facilityTier": "CHC",
    "latitude": 25.2352,
    "longitude": 87.5941,
    "totalGeneralBeds": 51,
    "availableGeneralBeds": 19,
    "totalIcuBeds": 7,
    "availableIcuBeds": 2,
    "totalVentilators": 0,
    "availableVentilators": 0,
    "hasVentilator": false,
    "hasTraumaSurgery": false,
    "hasBloodBank": false,
    "hasOxygenGenerator": true,
    "specialists": []
  },
  {
    "id": "jh-sadar-district-hospital-pakur",
    "name": "Sadar District Hospital Pakur",
    "shortCode": "SDHP",
    "districtName": "Pakur",
    "facilityTier": "DISTRICT",
    "latitude": 24.6246,
    "longitude": 87.8581,
    "totalGeneralBeds": 217,
    "availableGeneralBeds": 58,
    "totalIcuBeds": 28,
    "availableIcuBeds": 5,
    "totalVentilators": 17,
    "availableVentilators": 4,
    "hasVentilator": true,
    "hasTraumaSurgery": false,
    "hasBloodBank": true,
    "hasOxygenGenerator": true,
    "specialists": [
      "Pulmonologist"
    ]
  },
  {
    "id": "jh-community-health-centre-chc-block-1-pakur",
    "name": "Community Health Centre (CHC) Block 1 - Pakur",
    "shortCode": "CHCBP",
    "districtName": "Pakur",
    "facilityTier": "CHC",
    "latitude": 24.6353,
    "longitude": 87.7277,
    "totalGeneralBeds": 70,
    "availableGeneralBeds": 22,
    "totalIcuBeds": 4,
    "availableIcuBeds": 1,
    "totalVentilators": 2,
    "availableVentilators": 1,
    "hasVentilator": true,
    "hasTraumaSurgery": false,
    "hasBloodBank": false,
    "hasOxygenGenerator": true,
    "specialists": []
  },
  {
    "id": "jh-community-health-centre-chc-block-2-pakur",
    "name": "Community Health Centre (CHC) Block 2 - Pakur",
    "shortCode": "CHCBP",
    "districtName": "Pakur",
    "facilityTier": "CHC",
    "latitude": 24.5583,
    "longitude": 87.7753,
    "totalGeneralBeds": 50,
    "availableGeneralBeds": 23,
    "totalIcuBeds": 7,
    "availableIcuBeds": 2,
    "totalVentilators": 4,
    "availableVentilators": 1,
    "hasVentilator": true,
    "hasTraumaSurgery": false,
    "hasBloodBank": false,
    "hasOxygenGenerator": false,
    "specialists": []
  }
];

export function getHospitalsForDistrict(districtName: string): JharkhandHospitalFacility[] {
  if (!districtName || districtName === "ALL") {
    return JHARKHAND_79_HOSPITALS;
  }
  return JHARKHAND_79_HOSPITALS.filter(
    (h) => h.districtName.toLowerCase().includes(districtName.toLowerCase()) || districtName.toLowerCase().includes(h.districtName.toLowerCase())
  );
}

// Convert a JharkhandHospitalFacility into a Hospital domain model object for the triage engine
export function convertFacilityToHospital(f: JharkhandHospitalFacility, index: number, total: number): Hospital {
  const totalBeds = f.totalGeneralBeds + f.totalIcuBeds;
  const usedGeneral = Math.max(0, f.totalGeneralBeds - f.availableGeneralBeds);
  const usedIcu = Math.max(0, f.totalIcuBeds - f.availableIcuBeds);
  const usedBeds = usedGeneral + usedIcu;

  // Normalized 2D projection for Dijkstra Canvas (0 to 100)
  // Jharkhand Lat bounds: 22.0 to 25.5 -> y from 90 to 10
  // Jharkhand Lng bounds: 83.3 to 88.0 -> x from 10 to 90
  const x = Math.min(92, Math.max(8, Math.round(((f.longitude - 83.3) / 4.7) * 80 + 10)));
  const y = Math.min(92, Math.max(8, Math.round((1 - (f.latitude - 22.0) / 3.5) * 80 + 10)));

  return {
    id: f.id,
    name: f.name,
    short: f.shortCode,
    x,
    y,
    beds: { used: usedBeds, total: totalBeds },
    icuBeds: { used: usedIcu, total: f.totalIcuBeds },
    generalBeds: { used: usedGeneral, total: f.totalGeneralBeds },
    ventilators: { used: Math.max(0, f.totalVentilators - f.availableVentilators), total: f.totalVentilators },
    specialists: { used: Math.round(f.specialists.length * 0.7), total: f.specialists.length },
    specialistRoster: {
      pulmonologists: { total: f.specialists.includes("Pulmonologist") ? 3 : 0, available: f.specialists.includes("Pulmonologist") ? 1 : 0 },
      cardiologists: { total: f.specialists.includes("Cardiologist") ? 3 : 0, available: f.specialists.includes("Cardiologist") ? 1 : 0 },
      traumaSurgeons: { total: f.specialists.includes("Trauma Surgeon") ? 2 : 0, available: f.specialists.includes("Trauma Surgeon") ? 1 : 0 },
      generalPhysicians: { total: 6, available: 3 }
    }
  };
}

// Compute dynamic spatial road connectivity edges between facilities
export function generateInterconnectivityEdges(hospitals: Hospital[]): NetworkEdge[] {
  const edges: NetworkEdge[] = [];
  if (hospitals.length <= 1) return edges;

  // For each hospital, connect to its nearest 2-3 neighbors
  for (let i = 0; i < hospitals.length; i++) {
    const distances = [];
    const h1 = hospitals[i];
    const f1 = JHARKHAND_79_HOSPITALS.find((h) => h.id === h1.id);

    for (let j = 0; j < hospitals.length; j++) {
      if (i === j) continue;
      const h2 = hospitals[j];
      const f2 = JHARKHAND_79_HOSPITALS.find((h) => h.id === h2.id);

      let minutes = 15;
      if (f1 && f2) {
        // Haversine km
        const dLat = (f2.latitude - f1.latitude) * Math.PI / 180;
        const dLng = (f2.longitude - f1.longitude) * Math.PI / 180;
        const a = Math.sin(dLat/2) * Math.sin(dLat/2) +
          Math.cos(f1.latitude * Math.PI / 180) * Math.cos(f2.latitude * Math.PI / 180) *
          Math.sin(dLng/2) * Math.sin(dLng/2);
        const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a));
        const km = 6371 * c;
        minutes = Math.max(5, Math.round(km * 1.4)); // ~45 km/h ambulance speed
      } else {
        const dx = h1.x - h2.x;
        const dy = h1.y - h2.y;
        minutes = Math.max(6, Math.round(Math.sqrt(dx*dx + dy*dy) * 0.8));
      }

      distances.push({ toId: h2.id, minutes });
    }

    // Sort by shortest travel time
    distances.sort((a, b) => a.minutes - b.minutes);
    const k = Math.min(3, distances.length);
    for (let m = 0; m < k; m++) {
      const target = distances[m];
      const exists = edges.some(e => (e.fromId === h1.id && e.toId === target.toId) || (e.fromId === target.toId && e.toId === h1.id));
      if (!exists) {
        edges.push({ fromId: h1.id, toId: target.toId, minutes: target.minutes });
      }
    }
  }

  return edges;
}
